### ISSUE TITLE
Genomeconnect report script failure

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/genomeconnect-report#8]
The ClinVarGCReports.py python script is hanging (without exception) in the creat_scvHash() function, which may be a result of a data issue in the file it is processing from the ClinVar ftp sites. 

Since we don't have the genomeconnect google reports stood up yet, this issue needs to be resolves asap.

@dazzariti can you inform Jules or whoever is now expecting the GenomeConnect Excel reports that we are unable to create new ones since 4/30/23? And let me know the urgency on getting this back online. I'm not sure if they look at these weekly or monthly or ?. It would be helpful in prioritizing.

**Comment by dazzariti** [comment]
@larrybabb I did send her the 4/30 ones and let her know May wasn't available last week. I think it's ok to skip one month, but unless we're able to get her the Google-sheet based reports, I would say this is a high priority to fix, a lot of their workflows depend on it.

**Comment by larrybabb** [comment]
this is working now. @dazzariti i don't think you need to review, but I suppose if you look in the place we usually put these you should see the folder for the 5-14-23 clinvar version of the genomeconnect reports.

**Comment by dazzariti** [comment]
Looks good!

**Comment by dazzariti** [comment]
@larrybabb I didn't realize this initially but the two newest reports still aren't generating, those are the reports added in December 2022 (https://github.com/clingen-data-model/genomeconnect-report/issues/5) for GenomeConnect - Invitae Patient Insights Network and GenomeConnect - Brain Gene Registry

**Comment by dazzariti** [comment]
@larrybabb It looks like the GenomeConnect reports haven't run since May 20th, here is the most recent ones I can find in the Google bucket https://console.cloud.google.com/storage/browser/clinvar-reports/GCReports_05-20-2023?orgonly=true&project=clingen-dev&supportedpurview=organizationId&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false

**Comment by larrybabb** [comment]
@dazzariti I just fixed this and reran it for the 6/4/23 clinvar release. Please verify with [this set of reports](https://console.cloud.google.com/storage/browser/clinvar-reports/GCReports_06-04-2023?project=clingen-dev) and close this if it looks correct.

**Comment by dazzariti** [comment]
It looks like it's still missing the GenomeConnect - Invitae Patient Insights Network submitter

**Comment by larrybabb** [comment]
@dazzariti sorry about that, can you check again. This review process is obviously very helpful. I fixed the issue, re-ran and re-uploaded to the same folder above.

**Comment by dazzariti** [comment]
That worked!
